package httpx

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"io"
	"log"
	"os"
	"time"

	"github.com/labstack/echo/v4"
)

// ctxKey is the unexported key used to carry the request ID through the
// echo context + downstream logger.
type ctxKey int

const (
	ctxRequestID ctxKey = iota
	// CtxRequestID is exported as a header/echo key for symmetry.
	CtxRequestIDHeader = "X-Request-ID"
)

// RequestID returns the X-Request-ID value either set by an upstream
// proxy or generated by our middleware. Empty only before the middleware
// has run.
func RequestID(c echo.Context) string {
	if v, ok := c.Request().Context().Value(ctxRequestID).(string); ok {
		return v
	}
	return c.Request().Header.Get(CtxRequestIDHeader)
}

// LogEntry is the JSON shape written to stdout for every HTTP request.
// Keeping it a fixed struct (rather than a free-form map) gives log
// collectors a stable schema to index.
type LogEntry struct {
	Time       string `json:"time"`
	Level      string `json:"level"`
	Kind       string `json:"kind"` // "http", "error", "security"
	RequestID  string `json:"request_id"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Status     int    `json:"status"`
	LatencyMs  int64  `json:"latency_ms"`
	ActorID    string `json:"actor_id,omitempty"`
	Role       string `json:"role,omitempty"`
	Workstation string `json:"workstation,omitempty"`
	RemoteAddr string `json:"remote_addr,omitempty"`
	Error      string `json:"error,omitempty"`
}

// Logger is a minimal JSON-line logger writing to stderr by default.
// Callers may swap the Writer for tests.
type Logger struct {
	Out io.Writer
}

// DefaultLogger writes to stderr.
var DefaultLogger = &Logger{Out: os.Stderr}

// Write emits one JSON line. Failures fall back to the standard logger
// so we never silently drop security-relevant events.
func (l *Logger) Write(e LogEntry) {
	if e.Time == "" {
		e.Time = time.Now().UTC().Format(time.RFC3339Nano)
	}
	if e.Level == "" {
		e.Level = "info"
	}
	b, err := json.Marshal(e)
	if err != nil {
		log.Printf("log marshal: %v", err)
		return
	}
	b = append(b, '\n')
	if _, err := l.Out.Write(b); err != nil {
		log.Printf("log write: %v", err)
	}
}

// StructuredLogging is Echo middleware that produces a JSON-line log for
// every request. It also injects a request ID into the context so
// downstream handlers can correlate events.
func StructuredLogging(lg *Logger) echo.MiddlewareFunc {
	if lg == nil {
		lg = DefaultLogger
	}
	return func(next echo.HandlerFunc) echo.HandlerFunc {
		return func(c echo.Context) error {
			start := time.Now()
			req := c.Request()
			rid := req.Header.Get(CtxRequestIDHeader)
			if rid == "" {
				rid = newRequestID()
				req.Header.Set(CtxRequestIDHeader, rid)
			}
			// Attach to the context so handlers can embed it in errors.
			ctx := context.WithValue(req.Context(), ctxRequestID, rid)
			c.SetRequest(req.WithContext(ctx))
			c.Response().Header().Set(CtxRequestIDHeader, rid)

			err := next(c)

			status := c.Response().Status
			// Echo hasn't yet translated a returned *HTTPError into a
			// status code at the point this middleware observes the
			// response. Unwrap it so the log reflects the intended
			// wire-level status instead of a stale 200.
			if he, ok := err.(*echo.HTTPError); ok && he.Code != 0 {
				status = he.Code
			}
			entry := LogEntry{
				Kind:        "http",
				RequestID:   rid,
				Method:      req.Method,
				Path:        req.URL.Path,
				Status:      status,
				LatencyMs:   time.Since(start).Milliseconds(),
				Workstation: req.Header.Get("X-Workstation"),
				RemoteAddr:  req.RemoteAddr,
			}
			if sess := CurrentSession(c); sess != nil {
				entry.ActorID = sess.UserID
				entry.Role = sess.Role
			}
			if err != nil {
				entry.Error = err.Error()
			}
			switch {
			case status >= 500:
				entry.Level = "error"
			case status >= 400:
				entry.Level = "warn"
			default:
				if err != nil {
					entry.Level = "error"
				}
			}
			lg.Write(entry)
			return err
		}
	}
}

// newRequestID returns 8 bytes of random hex (16 chars). Enough entropy
// to correlate logs over a reasonable operational window.
func newRequestID() string {
	b := make([]byte, 8)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}
