// Package crypto provides at-rest encryption for sensitive fields
// (customer/patient identifiers, street addresses). Keys are loaded from the
// host environment per deployment; a production operator rotates them by
// adding a new versioned key and re-wrapping existing values.
package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/base64"
	"encoding/binary"
	"errors"
	"fmt"
	"strings"
)

// Errors exposed for the storage layer.
var (
	ErrKeyUnknown  = errors.New("crypto: referenced key version is unknown")
	ErrCiphertext  = errors.New("crypto: malformed ciphertext")
	ErrInvalidKey  = errors.New("crypto: key must be 32 bytes (AES-256)")
	ErrNoActiveKey = errors.New("crypto: no active key is configured")
)

// Vault holds one or more 32-byte AES keys identified by version. The
// highest-version key is used for new writes; older versions remain
// available for reads to support key rotation.
type Vault struct {
	keys   map[uint16][]byte
	active uint16
}

// NewVault constructs a vault from a map of version -> 32-byte key. The
// highest version number is treated as the active write key.
func NewVault(keys map[uint16][]byte) (*Vault, error) {
	if len(keys) == 0 {
		return nil, ErrNoActiveKey
	}
	v := &Vault{keys: make(map[uint16][]byte, len(keys))}
	var max uint16
	for ver, k := range keys {
		if len(k) != 32 {
			return nil, fmt.Errorf("%w (version %d)", ErrInvalidKey, ver)
		}
		v.keys[ver] = append([]byte(nil), k...)
		if ver > max {
			max = ver
		}
	}
	v.active = max
	return v, nil
}

// ActiveVersion reports the key version that will be used for new writes.
func (v *Vault) ActiveVersion() uint16 { return v.active }

// Encrypt returns a compact, self-describing envelope:
//
//	"v1:<base64(keyVersion||nonce||ciphertext)>"
//
// The key version is encoded so that rotation does not require schema changes.
// Returns an empty string unchanged so callers can pass optional fields.
func (v *Vault) Encrypt(plaintext string) (string, error) {
	if plaintext == "" {
		return "", nil
	}
	key, ok := v.keys[v.active]
	if !ok {
		return "", ErrNoActiveKey
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	nonce := make([]byte, aead.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", err
	}
	ct := aead.Seal(nil, nonce, []byte(plaintext), nil)
	blob := make([]byte, 2+len(nonce)+len(ct))
	binary.BigEndian.PutUint16(blob[:2], v.active)
	copy(blob[2:], nonce)
	copy(blob[2+len(nonce):], ct)
	return "v1:" + base64.RawStdEncoding.EncodeToString(blob), nil
}

// Decrypt reverses Encrypt. An empty input produces an empty output.
func (v *Vault) Decrypt(envelope string) (string, error) {
	if envelope == "" {
		return "", nil
	}
	if !strings.HasPrefix(envelope, "v1:") {
		return "", ErrCiphertext
	}
	blob, err := base64.RawStdEncoding.DecodeString(envelope[3:])
	if err != nil {
		return "", ErrCiphertext
	}
	if len(blob) < 2+12+16 {
		return "", ErrCiphertext
	}
	ver := binary.BigEndian.Uint16(blob[:2])
	key, ok := v.keys[ver]
	if !ok {
		return "", ErrKeyUnknown
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return "", err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return "", err
	}
	nonceSize := aead.NonceSize()
	if len(blob) < 2+nonceSize {
		return "", ErrCiphertext
	}
	nonce := blob[2 : 2+nonceSize]
	ct := blob[2+nonceSize:]
	pt, err := aead.Open(nil, nonce, ct, nil)
	if err != nil {
		return "", ErrCiphertext
	}
	return string(pt), nil
}

// DeriveKey fills out a 32-byte key from a raw byte slice by padding with
// zeros or truncating. Intended only for tests and bootstrap; production keys
// are generated by a keygen tool (see cmd/keygen/main.go).
func DeriveKey(material []byte) []byte {
	out := make([]byte, 32)
	copy(out, material)
	return out
}
